version: '3'
services:
  sync:
    depends_on:
      - call-logd
      - swagger-validator
    environment:
      TARGETS: "call-logd:9298 swagger-validator:8080"

  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"
